name: WordPress Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WordPress Theme/Plugin Sync
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.WORDPRESS_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WORDPRESS_SVN_USERNAME }}
          SLUG: tinytreasurehunter